version: '3.9'

services:

  postgres:
    image: postgres:16

    container_name: postgres-login

    environment:
      POSTGRES_DB: login
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 14582645

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: api-login

    depends_on:
      - postgres

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/login
      DB_USER: postgres
      DB_PASSWORD: 14582645

    ports:
      - "8080:8080"

volumes:
  postgres_data: