spring.application.name=login-usuarios
server.servlet.context-path=/login-usuarios/v1
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/login}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.mail.host=smtp.gmail.com
spring.mail.port=465

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

api.token.secret=${JWT_SECRET:MinhaChaveSuperSecretaComMaisDe32Caracteres123456}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=8080
