spring.application.name=login-usuarios
server.servlet.context-path=/login-usuarios/v1
spring.datasource.url=${DB_URL:phaceolder}
spring.datasource.username=${DB_USER:phaceolder}
spring.datasource.password=${DB_PASSWORD:phaceolder}

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:phaceolder}
spring.mail.password=${MAIL_PASSWORD:phaceolder}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

mail.from=${MAIL_FROM:phaceolder}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

api.token.secret=${JWT_SECRET:phaceolder}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.flyway.enabled=true

server.port=8080
