spring.application.name=login-usuarios
server.servlet.context-path=/login-usuarios/v1
spring.datasource.url=${DB_URL:phaceolder}
spring.datasource.username=${DB_USER:phaceolder}
spring.datasource.password=${DB_PASSWORD:phaceolder}

brevo.api.key=${MAIL_PASSWORD:phaceolder}
brevo.from.email=${MAIL_FROM:phaceolder}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

api.token.secret=${JWT_SECRET:MinhaChaveSuperSecretaComMaisDe32Caracteres123456}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=8080
